String styleJSON = '''
{
  "version": 8,
  "name": "Basic",
  "constants": {},
  "sources": {
    "gsibv-vectortile-source-1-4-16": {
      "type": "vector",
      "tiles": [
        "https://cyberjapandata.gsi.go.jp/xyz/experimental_bvmap/{z}/{x}/{y}.pbf"
      ],
      "attribution": "",
      "minzoom": 4,
      "maxzoom": 16
    }
  },
  "sprite": "",
  "glyphs": "",
  "layers": [
{"id":"gsibv-vectortile-layer-1","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"structurel","metadata":{"layer-id":"layer-29","title":"坑口","path":"構造物-坑口","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",4202]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1.5}},
{"id":"gsibv-vectortile-layer-2","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-289","title":"人工水路（地下）","path":"河川-人工水路（地下）","added":1},"minzoom":8,"maxzoom":14,"filter":["all",["in","ftCode",5322]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(190,210,255)","line-width":{"stops":[[9,1],[17,2]]},"line-dasharray":[2,2]}},
{"id":"gsibv-vectortile-layer-3","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-290","title":"人工水路（地下）","path":"河川-人工水路（地下）","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5322]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1.5,"line-dasharray":[5,5]}},
{"id":"gsibv-vectortile-layer-4","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-284","title":"枯れ川部","path":"河川-枯れ川部","added":1},"minzoom":8,"maxzoom":14,"filter":["all",["in","ftCode",5302]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(190,210,255)","line-width":{"stops":[[9,1],[17,2]]},"line-dasharray":[2,2]}},
{"id":"gsibv-vectortile-layer-5","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-285","title":"枯れ川部","path":"河川-枯れ川部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5302]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1.5,"line-dasharray":[5,1.5]}},
{"id":"gsibv-vectortile-layer-6","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-286","title":"枯れ川部","path":"河川-枯れ川部","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5302]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1}},
{"id":"gsibv-vectortile-layer-7","type":"fill","source":"gsibv-vectortile-source-1-4-16","source-layer":"waterarea","metadata":{"layer-id":"layer-1","title":"水域","path":"水域","added":1},"minzoom":4,"maxzoom":17,"filter":["all",["in","ftCode",55000,5000]],"layout":{"visibility":"visible"},"paint":{"fill-color":"rgb(190,210,255)"}},
{"id":"gsibv-vectortile-layer-8","type":"fill","source":"gsibv-vectortile-source-1-4-16","source-layer":"waterarea","metadata":{"layer-id":"layer-2","title":"水域","path":"水域","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5000]],"layout":{"visibility":"visible"},"paint":{"fill-color":"rgb(254,254,255)"}},
{"id":"gsibv-vectortile-layer-9","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-19","title":"湖底急斜面","path":"地形-湖底急斜面","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7571]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(43,107,255,1)","line-width":1}},
{"id":"gsibv-vectortile-layer-10","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"lake","metadata":{"layer-id":"layer-291","title":"通常部","path":"湖池-通常部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5231]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1}},
{"id":"gsibv-vectortile-layer-11","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"lake","metadata":{"layer-id":"layer-292","title":"通常部","path":"湖池-通常部","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5231]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":0.5}},
{"id":"gsibv-vectortile-layer-13","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"lake","metadata":{"layer-id":"layer-294","title":"堤防等に接する部分","path":"湖池-堤防等に接する部分","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5233]],"layout":{"line-cap":"round","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1.5,"line-dasharray":[0.2,4]}},
{"id":"gsibv-vectortile-layer-14","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"lake","metadata":{"layer-id":"layer-294","title":"堤防等に接する部分","path":"湖池-堤防等に接する部分","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5233]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1,"line-offset":-1}},
{"id":"gsibv-vectortile-layer-15","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"lake","metadata":{"layer-id":"layer-295","title":"堤防等に接する部分","path":"湖池-堤防等に接する部分","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5233]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1}},
{"id":"gsibv-vectortile-layer-16","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-282","title":"堤防等に接する部分","path":"河川-堤防等に接する部分","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5203]],"layout":{"line-cap":"round","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1.5,"line-dasharray":[0.2,4]}},
{"id":"gsibv-vectortile-layer-17","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-282","title":"堤防等に接する部分","path":"河川-堤防等に接する部分","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5203]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1,"line-offset":-1}},
{"id":"gsibv-vectortile-layer-18","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-283","title":"堤防等に接する部分","path":"河川-堤防等に接する部分","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5203]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1}},
{"id":"gsibv-vectortile-layer-19","type":"fill","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforma","metadata":{"layer-id":"layer-3","title":"湿地","path":"地形-湿地","added":1},"minzoom":8,"maxzoom":14,"filter":["all",["in","ftCode",7401]],"layout":{"visibility":"visible"},"paint":{"fill-color":"rgba(153,238,192,1)"}},
{"id":"gsibv-vectortile-layer-20","type":"fill","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforma","metadata":{"layer-id":"layer-4","title":"湿地","path":"地形-湿地","gsi-fill-hatch-style":"minus","fill-color":"rgba(20,90,255,1)","added":1,"fill-pattern":"-gsibv-hatch-minus-12-20,90,255,1-"},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7401]],"layout":{"visibility":"visible"},"paint":{"fill-color":"rgba(153,183,255,1)"}},
{"id":"gsibv-vectortile-layer-21","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-279","title":"通常部","path":"河川-通常部","added":1},"minzoom":8,"maxzoom":14,"filter":["all",["in","ftCode",5301]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(190,210,255)","line-width":1}},
{"id":"gsibv-vectortile-layer-22","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-280","title":"通常部","path":"河川-通常部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5201,5301]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1}},
{"id":"gsibv-vectortile-layer-23","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-281","title":"通常部","path":"河川-通常部","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5201,5301]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1}},
{"id":"gsibv-vectortile-layer-24","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-275","title":"河川幅(大)","path":"河川-河川幅(大)","added":1},"minzoom":6,"maxzoom":8,"filter":["all",["in","ftCode",55301]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(0,176,236)","line-width":{"stops":[[6,2],[7,2.5]]}}},
{"id":"gsibv-vectortile-layer-25","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-276","title":"河川幅(中)","path":"河川-河川幅(中)","added":1},"minzoom":6,"maxzoom":8,"filter":["all",["in","ftCode",55302]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(0,176,236)","line-width":{"stops":[[6,1.5],[7,2]]}}},
{"id":"gsibv-vectortile-layer-26","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-277","title":"河川幅(小)","path":"河川-河川幅(小)","added":1},"minzoom":6,"maxzoom":8,"filter":["all",["in","ftCode",55303]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(0,176,236)","line-width":{"stops":[[6,1],[7,1.5]]}}},
{"id":"gsibv-vectortile-layer-27","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"river","metadata":{"layer-id":"layer-278","title":"河川幅(極小)","path":"河川-河川幅(極小)","added":1},"minzoom":6,"maxzoom":8,"filter":["all",["in","ftCode",55304]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(0,176,236)","line-width":{"stops":[[6,0.5],[7,1]]}}},
{"id":"gsibv-vectortile-layer-28","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-270","title":"通常部","path":"海岸線-通常部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5101]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(20,90,255)","line-width":1}},
{"id":"gsibv-vectortile-layer-29","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-271","title":"通常部","path":"海岸線-通常部","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5101]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":0.5}},
{"id":"gsibv-vectortile-layer-31","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-273","title":"堤防等に接する部分","path":"海岸線-堤防等に接する部分","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5103]],"layout":{"line-cap":"round","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1.5,"line-dasharray":[0.2,4]}},
{"id":"gsibv-vectortile-layer-32","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-273","title":"堤防等に接する部分","path":"海岸線-堤防等に接する部分","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",5103]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1,"line-offset":-1}},
{"id":"gsibv-vectortile-layer-33","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-274","title":"堤防等に接する部分","path":"海岸線-堤防等に接する部分","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5103]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1.5,"line-dasharray":[0.2,4]}},
{"id":"gsibv-vectortile-layer-34","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-274","title":"堤防等に接する部分","path":"海岸線-堤防等に接する部分","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",5103]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(100,100,100,1)","line-width":1,"line-offset":-1}},
{"id":"gsibv-vectortile-layer-35","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"coastline","metadata":{"layer-id":"layer-269","title":"海岸線","path":"海岸線-海岸線","added":1},"minzoom":4,"maxzoom":8,"filter":["all",["in","ftCode",55101]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgb(0,176,236)","line-width":1}},
{"id":"gsibv-vectortile-layer-36","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-17","title":"枯れ川水涯線","path":"地形-枯れ川水涯線","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7561]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(43,107,255,1)","line-width":1,"line-dasharray":[4,4]}},
{"id":"gsibv-vectortile-layer-37","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-18","title":"枯れ川水涯線","path":"地形-枯れ川水涯線","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",7561]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(43,107,255,1)","line-width":2,"line-dasharray":[4,4]}},
{"id":"gsibv-vectortile-layer-38","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-15","title":"干潟界","path":"地形-干潟界","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7551]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":1,"line-dasharray":[5,5]}},
{"id":"gsibv-vectortile-layer-39","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-16","title":"干潟界","path":"地形-干潟界","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",7551]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":1.5,"line-dasharray":[4,1]}},
{"id":"gsibv-vectortile-layer-40","type":"fill","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforma","metadata":{"layer-id":"layer-5","title":"万年雪","path":"地形-万年雪","gsi-fill-hatch-style":"dot","fill-color":"rgba(20,90,255,1)","added":1,"fill-pattern":"-gsibv-hatch-dot-4-20,90,255,1-"},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7402]],"layout":{"visibility":"visible"},"paint":{"fill-color":"rgba(153,183,255,1)"}},
{"id":"gsibv-vectortile-layer-41","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"contour","metadata":{"layer-id":"layer-303","title":"通常部","path":"等高線等深線-等深線-通常部","added":1},"minzoom":11,"maxzoom":14,"filter":["all",["in","ftCode",7371,7373]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":0.7}},
{"id":"gsibv-vectortile-layer-42","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"contour","metadata":{"layer-id":"layer-304","title":"計曲線通常部","path":"等高線等深線-等深線-計曲線通常部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7371],["any",["==","altiFlag",0],["==","depthFlag",0]]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":1.4}},
{"id":"gsibv-vectortile-layer-43","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"contour","metadata":{"layer-id":"layer-305","title":"主曲線通常部","path":"等高線等深線-等深線-主曲線通常部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7371],["any",["==","altiFlag",1],["==","depthFlag",1]]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":0.7}},
{"id":"gsibv-vectortile-layer-44","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"contour","metadata":{"layer-id":"layer-306","title":"補助曲線通常部","path":"等高線等深線-等深線-補助曲線通常部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7371],["any",["==","altiFlag",2],["==","depthFlag",2]]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":0.7,"line-dasharray":[40,3]}},
{"id":"gsibv-vectortile-layer-45","type":"symbol","source":"gsibv-vectortile-source-1-4-16","source-layer":"contour","metadata":{"layer-id":"layer-309","title":"数値部","path":"等高線等深線-等深線-数値部","added":1},"minzoom":11,"maxzoom":17,"filter":["all",["in","ftCode",7372]],"layout":{"text-allow-overlap":true,"text-ignore-placement":true,"text-keep-upright":true,"symbol-placement":"line","text-max-width":999,"text-rotate":0,"text-anchor":"center","text-padding":0,"text-pitch-alignment":"viewport","text-rotation-alignment":"viewport","icon-pitch-alignment":"viewport","icon-rotation-alignment":"viewport","text-offset":["case",["==",["get","arrng"],2],["case",["any",["==",["get","dspPos"],"CB"],["==",["get","dspPos"],"RB"],["==",["get","dspPos"],"LB"]],["literal",[0.5,0]],["any",["==",["get","dspPos"],"CT"],["==",["get","dspPos"],"RT"],["==",["get","dspPos"],"LT"]],["literal",[-0.5,0]],["any",["==",["get","dspPos"],"LC"]],["literal",[0,0.5]],["any",["==",["get","dspPos"],"RC"]],["literal",[0,-0.5]],["literal",[0,0]]],["case",["any",["==",["get","dspPos"],"LT"],["==",["get","dspPos"],"LC"],["==",["get","dspPos"],"LB"]],["literal",[0.5,0]],["any",["==",["get","dspPos"],"RT"],["==",["get","dspPos"],"RC"],["==",["get","dspPos"],"RB"]],["literal",[-0.5,0]],["any",["==",["get","dspPos"],"CT"]],["literal",[0,0.5]],["any",["==",["get","dspPos"],"CB"]],["literal",[0,-0.5]],["literal",[0,0]]]],"text-size":13,"text-field":["get",["case",["has","depth"],"depth","alti"]],"text-font":["NotoSansCJKjp-Regular"],"icon-allow-overlap":true,"symbol-z-order":"auto","visibility":"visible"},"paint":{"text-color":"rgba(20,90,255,1)","text-halo-color":"rgb(190,210,255)","text-halo-width":10}},
{"id":"gsibv-vectortile-layer-46","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"contour","metadata":{"layer-id":"layer-307","title":"計曲線崖部","path":"等高線等深線-等深線-計曲線崖部","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7373],["any",["==","altiFlag",0],["==","depthFlag",0]]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(20,90,255,1)","line-width":1.4}},
{"id":"gsibv-vectortile-layer-48","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-13","title":"岩・崖等","path":"地形-岩・崖等","added":1},"minzoom":14,"maxzoom":17,"filter":["all",["in","ftCode",7501,7502,7509,7511,7512,7541]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(200,160,60,1)","line-width":{"stops":[[14,1],[17,2]]}}},
{"id":"gsibv-vectortile-layer-49","type":"line","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforml","metadata":{"layer-id":"layer-14","title":"岩・崖等","path":"地形-岩・崖等","added":1},"minzoom":17,"maxzoom":18,"filter":["all",["in","ftCode",7501,7502,7509,7511,7512,7541]],"layout":{"line-cap":"square","visibility":"visible"},"paint":{"line-color":"rgba(200,160,60,1)","line-width":2}},
{"id":"gsibv-vectortile-layer-50","type":"fill","source":"gsibv-vectortile-source-1-4-16","source-layer":"landforma","metadata":{"layer-id":"layer-6","title":"砂礫地（領域が明瞭な場合）","path":"地形-砂礫地（領域が明瞭な場合）","gsi-fill-hatch-style":"dot","fill-color":"rgba(200, 160, 60,1)","added":1,"fill-pattern":"-gsibv-hatch-dot-4-200,160,60,1-"},"minzoom":8,"maxzoom":17,"filter":["all",["in","ftCode",7403]],"layout":{"visibility":"visible"},"paint":{"fill-color":"rgba(233,216,175,1)"}}
  ]
}
''';
